---
version: '3.8'
services:
  to-jaeger:
    container_name: to-jaeger
    image: jaegertracing/all-in-one:1.57
    # see:
    # https://www.jaegertracing.io/docs/next-release/getting-started/#all-in-one
    #
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"
      - "16686:16686" # http://localhost:16686
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "14250:14250"
...
